# Generated by Django 3.1.7 on 2021-04-08 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210408_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 20, 46, 42, 866210), verbose_name='create date'),
        ),
    ]
